### ISSUE TITLE
video output is faster

### ISSUE THREAD

**Issue by Samad08** [Bammuri/Lab_project#1]
I took some help from your multi-record code and I am using the same 30 FPS for depth and RGB but my output video looks like a fast forward version. I am using XVID in the fourcc function (also with 30 fps) and my output format is .avi
Can you please tell me how can I make it to record it in a normal way.

**Comment by Samad08** [comment]
No answer

**Comment by Bammuri** [comment]
@Samad08  Sorry, I was busy, so I checked now. 

Can I know the camera model?
Please report more specific errors.
Did you fix my code?

**Comment by Samad08** [comment]
Thank you for your reply. 
Your code helped a lot, I would like to thank you first.

Camera model is D435i.
Actually there is no error, it works fine the only problem is with my recorded videos which i saved with 30 fps & fourcc('X','V','I','D'), when i play the videos they play as if i am playing it 2 times the normal speed.

**Comment by Bammuri** [comment]
Thank you. :)  
I'm glad it helped.
So, are there any other problems?

**Comment by Samad08** [comment]
Nope, the playing speed of the video doesn't matter now :)
